name: mystic_crawler
description: Mystic crawler
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  shared_preferences: 2.5.2
  injectable: 2.5.0
  get_it: 8.0.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: 2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
